name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - stage
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write


jobs:

# resolving the environment


  resolve-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}

    steps:
      - name: Resolve environment
        id: set-env
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/dev ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/stage ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi  
    
 

   # building .zip and uploading lambda artifact



  build-lambda:

    needs: resolve-environment
    runs-on: ubuntu-latest

    environment: ${{ needs.resolve-environment.outputs.environment }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
         rm -rf lambda/package
         mkdir -p lambda/package
         pip install -r lambda/requirements.txt -t lambda/package

      - name: Copy source files
        run: |
         cp -r lambda/src/* lambda/package/

      - name: Create Lambda zip
        run: |
         cd lambda/package
         zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PIPELINE_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact to S3
        run: |
          ENV_NAME=${{ needs.resolve-environment.outputs.environment }}
          aws s3 cp lambda/lambda.zip \
          s3://${{ vars.LAMBDA_ARTIFACT_BUCKET }}/${ENV_NAME}/${{ github.sha }}.zip        
  


   # creating dependencies for ordered deployment


  networking:

    needs: resolve-environment
    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: networking
      action: apply


  iam:

    needs: [resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: iam
      action: apply


  database:

    needs: [iam, networking, resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: database
      action: apply


  s3:

    needs: [resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: s3
      action: apply


  lambda:

    needs: [build-lambda, s3, iam, networking, database, resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: lambda
      action: apply


  api_gateway:

    needs: [lambda, resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: api
      action: apply


  cloudfront:

    needs: [api_gateway, s3, resolve-environment]

    uses: ./.github/workflows/terraform-component.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      component: cloudfront
      action: apply