name: Terraform Component

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      component:
        required: true
        type: string
      action:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  terraform:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PIPELINE_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: Setup Terraform plugin cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc


      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-


      - name: Terraform Init
        run: terraform init
        working-directory: environments/${{ inputs.environment }}/${{ inputs.component }}


      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: |
          terraform plan \
          -var-file="../terraform.tfvars" \
          -no-color | tee plan.txt
        working-directory: environments/${{ inputs.environment }}/${{ inputs.component }}


      - name: Fail if destroy detected
        if: inputs.action == 'plan'
        run: |
          if grep -q "will be destroyed" plan.txt; then
            echo "Terraform plan contains destroy actions. Failing pipeline."
            exit 1
          fi
        working-directory: environments/${{ inputs.environment }}/${{ inputs.component }}


      - name: Upload Terraform Plan
        if: inputs.action == 'plan'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ inputs.component }}
          path: environments/${{ inputs.environment }}/${{ inputs.component }}/plan.txt


      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: |
          ENV_NAME=${{ inputs.environment }}

          if [ "${{ inputs.component }}" = "lambda" ]; then
            terraform apply \
              -var-file="../terraform.tfvars" \
              -var="artifact_key=${ENV_NAME}/${{ github.sha }}.zip" \
              -auto-approve
          else    
            terraform apply \
              -var-file="../terraform.tfvars" \
              -auto-approve
          fi    
        working-directory: environments/${{ inputs.environment }}/${{ inputs.component }}